version: "3.8"

services:
  pyraws:
    image: pyraws:latest
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace/
    platform: linux/amd64

    command: sleep infinity