#!/bin/bash

events=(
    # 'Barren_Island_00'
    # 'Barren_Island_01'
    # 'Barren_Island_02'
    # 'Barren_Island_10'
    # 'Chillan_Nevados_de_01'
    # 'Chillan_Nevados_de_02'
    # 'Copahue_20'
    # 'Copahue_21_NE'
    # 'Etna_00'
    # 'Etna_01'
    # 'Etna_02'
    # 'Etna_03'
    # 'Fuego_00'
    # 'Fuego_01'
    # 'Fuego_02'
    # 'Karangetang_01'
    # 'Krysuvik-Trolladyngja_00'
    # 'Krysuvik-Trolladyngja_01'
    # 'Krysuvik-Trolladyngja_02'
    # 'Krysuvik-Trolladyngja_03'
    # 'La_Palma_00'
    # 'La_Palma_02'
    # 'Mayon_01'
    # 'Mayon_02'
    'Nyamulagira_00'
    'Nyamulagira_01'
    'Nyamulagira_02'
    'Piton_de_la_Fournaise_00'
    'Piton_de_la_Fournaise_01'
    'Piton_de_la_Fournaise_02'
    'Piton_de_la_Fournaise_10'
    'Piton_de_la_Fournaise_11'
    'Piton_de_la_Fournaise_12'
    'Piton_de_la_Fournaise_31'
    'Piton_de_la_Fournaise_32'
    'Raung_10'
    'Raung_11'
    'Raung_12'
    'San_Miguel_10'
    'San_Miguel_11'
    'San_Miguel_12'
    'Sangay_00'
    'Sangay_01'
    'Sangay_10'
    'Sangay_11'
    'Sangay_12'
    'Sangay_31'
    'Santa_Maria_00'
    'Stromboli_01'
    'Stromboli_02'
    'Telica_00'
    'Telica_02'
    'Tinakula_00'
    'Tinakula_01'
    'Tinakula_02'
    'Nyamulagira_03'
    'Nyamulagira_04'
    'Nyamulagira_05'
    'Poas_00'
    'Piton_de_la_Fournaise_00_NE'
    'Piton_de_la_Fournaise_02_NE'
    'Poas_20_NE'
    'Raung_10_NE'
    'Raung_11_NE'
    'Raung_12_NE'
    'Telica_00_NE'
    'Telica_01_NE'
    'Ulawun_20_NE'
    'France_0'
    'Greece_0'
    'Greece_1'
    'Greece_2'
    'Latvia_0'
    'Mexico_0'
    'Spain_2'
    'Greece_3'
    'Ukraine_0'
    'Australia_1'
    'Italy_0'
    'Bolivia_0'
    'Bolivia_1'
    'Greece_4'
    'Greenland_0'
    'Greece_5'
    'Kenya_0'
    'Latvia_1'
    'Sweden_0'
    'Spain_5'
)

for event in "${events[@]}"
do
    for overlap in 0.25 0.33 0.5 0.75
    do
        for windowSize in "(128,128)" "(256,256)" "(384,384)" "(512,512)"
        do
            python ps.py --event "$event" --img_size="(1400,1400)" --overlap "$overlap" --windowSize="$windowSize" --plot False
        done
    done
done